### PR TITLE
added the scam urls, trailing slashes and terms as arrays / lists

### PR DESCRIPTION
**Pull request by NotFaizen**

### CODE REVIEW

**Comment by Horziox** [comment]
And we have this too `sweatco.in`  !

**Comment by DevSpen** [comment]
> I think the best idea is to leave the choice and therefore put txt or json (array) If someone for exemple use this [links](https://raw.githubusercontent.com/DevSpen/scam-links/master/src/links.txt) (which is automatically updated), it might break a lot of things
> 
> And also less practical since it will be necessary to edit at least 2 files at the same time or 6

I agree.

With the upcoming API, it will offer an endpoint for object output of links (and other lists).

I fear that it will be less contributor friendly if there are multiple files to update just to add one link.

**Comment by Horziox** [comment]
> With the upcoming API, it will offer an endpoint for object output of links (and other lists).
Do you really think the api is really useful and not a bit overkill?

**Comment by DevSpen** [comment]
> > With the upcoming API, it will offer an endpoint for object output of links (and other lists).
> > Do you really think the api is really useful and not a bit overkill?

Imo no, it'd be quite helpful for a lot of use-cases, and won't require as much work to integrate the list to your own projects.

**Comment by DevSpen** [comment]
I'm closing this for now, if anyone wants to give their thoughts then feel free. I may reopen it in the future but for now, I'm closing it for the reason stated [here](https://github.com/DevSpen/scam-links/pull/38#issuecomment-1015859499).

**Pull request closed without merging**
