### PR TITLE
New batch of links

### PR DESCRIPTION
**Pull request by PyAres**
I decided to casually check a bit my message requests to see what scam links goin on around and this is what i "looted"

### CODE REVIEW

**Comment by PyAres** [comment]
Well seems like it's useless to open new prs on this repo, from now on i'm just gonna update my fork

**Comment by DevSpen** [comment]
> Well seems like it's useless to open new prs on this repo, from now on i'm just gonna update my fork

Sorry for the break in work, I’m going to continue to check PRs now

**Comment by JeDaYoshi** [comment]
Just briefly glancing on this, I can see for example `yobit.net` was added which is not specifically a scam domain, just used by spammers.

**Comment by DevSpen** [comment]
> Just briefly glancing on this, I can see for example `yobit.net` was added which is not specifically a scam domain, just used by spammers.

**Comment by JeDaYoshi** [comment]
That doesn't mean all domains included on this PR are invalid, though.

**Comment by DevSpen** [comment]
> That doesn't mean all domains included on this PR are invalid, though.

Yes, sorry I miss clicked to close

**Pull request closed without merging**
