### PR TITLE
add link

### PR DESCRIPTION
**Pull request by Qxe5**
**Reason**

image

**Question**

I use this list as apart of my Discord bot (https://github.com/Qxe5/asca). I would like to add logging for messages it detects as scams but are **not** in this list for me to review and contribute to this project. I just need to know what is the minimal amount of data you would need from me to justify inclusion in the list. Would the message alone be sufficient?

### CODE REVIEW

**Comment by DevSpen** [comment]
> I use this list as apart of my Discord bot (https://github.com/Qxe5/asca). I would like to add logging for messages it detects as scams but are **not** in this list for me to review and contribute to this project. I just need to know what is the minimal amount of data you would need from me to justify inclusion in the list. Would the message alone be sufficient?

Hey there, I didn't really understand your question. Could you try rephrasing it a bit?

**Comment by Qxe5** [comment]
Hey sure no problem, 

This pull request is just for the one link.

The question was about future contributions, basically is a discord message alone (without server/channel information) enough justification for inclusion onto the list of links?

I plan to use my Discord bot to help me contribute here. It is in a couple of high traffic servers (85k+ members).

**Comment by Qxe5** [comment]
For example, would this be okay when I contribute links:

Link A

```Message```

Link B 

```Message```

etc.

**Comment by Qxe5** [comment]
Related: https://github.com/DevSpen/scam-links/pull/41

I'm doing the same thing as the user who made this pull request.

**Comment by DevSpen** [comment]
> Hey sure no problem,
> 
> This pull request is just for the one link.
> 
> The question was about future contributions, basically is a discord message alone (without server/channel information) enough justification for inclusion onto the list of links?
> 
> I plan to use my Discord bot to help me contribute here. It is in a couple of high traffic servers (85k+ members).

We do not require screenshots or anything as such. It is usually pretty obvious what are links are scams, and which are not. With that being said, for the ones that aren't obvious, I'll manually check them. Hope that answers your question.

And thank you for wanting to contribute, this repo is only viable because of the contributors.

_If you need extra help integrating or contributing to the list, you can always contact me via DM (`Spen#0999`), or @mention me a PR_

**Pull request merged**
